import * as THREE from 'three';
import {OrbitControls} from '/vendor/OrbitControls.js';
const $=id=>document.getElementById(id), esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={CONFIRMED:'已确认',TENTATIVE:'待确认',MISSING_CANDIDATE:'疑似移除',VACATED:'已清空',VISIBLE:'可见',OCCLUDED:'被遮挡',UNKNOWN:'未知',MEASURED:'实测',PRIOR_ESTIMATED:'先验推算',RETAINED:'沿用历史',UNAVAILABLE:'不可用',RESOLVED:'已关联',LOCATION_REOCCUPIED:'原位置重新占用',PRESENT:'表面仍在',CLEAR:'原生射线穿过',PATCH_CLEARED:'只清空局部面',MATCHED:'匹配旧 ID',NEW_CANDIDATE:'新箱候选',GEOMETRY_UNKNOWN:'几何不合格',LAYER_CHANGE_PENDING:'前后层待核验',IDENTITY_AMBIGUOUS:'编号冲突',DETECTOR_SPLIT:'检测分裂',DETECTOR_MERGE:'检测合并',REDUNDANT_MERGE:'多余合并框',COMMITTED:'提交成功',PAUSED:'计算已暂停',READ_ONLY_OR_UNSTABLE_CAPTURE:'只读或未稳定',RECORDED_SCAN_STABILITY_UNVERIFIED:'录制帧缺少扫描稳定性证据，禁止提交',RETURN_SEMANTICS_UNVERIFIED:'首回波语义未确认，不能判整箱清空',INSUFFICIENT_COVERAGE:'有效射线覆盖不足',REFERENCE_NOT_MEASURED:'没有可信实测参考面',MEASURED_FACE_SUPPORTED:'实测箱面得到支持',NATIVE_RAYS_THROUGH_MEASURED_FACE:'原生射线穿过实测箱面',NEARER_RETURN:'有更近的返回表面'};
const tr=x=>names[x]||x||'—', xyz=a=>a?a.map(x=>Number(x).toFixed(3)).join(', '):'不可用';
let state=null,lastScene=null,lastRevision=null,fitOnce=false;
async function command(cmd){try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cmd)});const body=await r.json();$('command').textContent=r.ok?'命令已排队':body.error;}catch(e){$('command').textContent=e.message;}}
function ids(){return $('targets').value.split(/[ ,，]+/).filter(Boolean).map(x=>{if(!/^\d+$/.test(x))throw Error('ID 必须是非负整数');return Number(x)});}
$('mode').onchange=()=>command({action:'mode',mode:$('mode').value});$('step').onclick=()=>command({action:'step'});$('save').onclick=()=>command({action:'save'});
$('ready').onchange=()=>command({action:'robot_ready',ready:$('ready').checked});$('newSession').onclick=()=>{if(confirm('保存当前历史并开始新的定位会话？旧 ID 不会自动跨定位会话关联。'))command({action:'new_session'});};
document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{try{command({action:'session',kind:b.dataset.session,target_ids:ids()});}catch(e){$('command').textContent=e.message}});
$('batch').onclick=()=>{try{command({action:'wall_batch',target_ids:ids()});}catch(e){$('command').textContent=e.message}};
$('ack').onclick=()=>{const s=state?.scheduler.session;if(s)command({action:'ack',view:s.views[s.view_index]});};$('cancel').onclick=()=>command({action:'cancel'});
$('setRegion').onclick=()=>{try{command({action:'region',corners:JSON.parse($('region').value)});}catch(e){$('command').textContent=e.message}};
$('sendAdvanced').onclick=()=>{try{command(JSON.parse($('advanced').value));}catch(e){$('command').textContent=e.message}};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();command({action:'step'});}});
const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));$('scene').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(55,1,.02,100);camera.up.set(0,0,1);camera.position.set(4,-5,3);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
const grid=new THREE.GridHelper(10,20,0x38536b,0x233142);grid.rotation.x=Math.PI/2;scene.add(grid);scene.add(new THREE.AxesHelper(.5));
const rawGroup=new THREE.Group(),expectedGroup=new THREE.Group(),boxGroup=new THREE.Group();scene.add(rawGroup,expectedGroup,boxGroup);
function dispose(group){for(const child of [...group.children]){child.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});group.remove(child);}}
function pointObject(points,colors,size=.018){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points.flat(),3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors.flat(),3));return new THREE.Points(g,new THREE.PointsMaterial({size,vertexColors:true}));}
function label(text,pos,color){const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='#0c1526';ctx.fillRect(0,0,256,64);ctx.fillStyle=color;ctx.font='bold 36px sans-serif';ctx.textAlign='center';ctx.fillText(text,128,45);const texture=new THREE.CanvasTexture(c);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));sprite.position.fromArray(pos);sprite.scale.set(.4,.1,1);return sprite;}
const palette=[[0,0,0],[.62,.67,.74],[.33,.87,.60],[.96,.68,.28],[.89,.39,.70],[.9,.15,.15],[.8,.25,.2]];
function drawScene(data){dispose(rawGroup);dispose(expectedGroup);rawGroup.add(pointObject(data.points||[],(data.labels||[]).map(i=>palette[i]||palette[1])));for(const points of Object.values(data.expected||{}))expectedGroup.add(pointObject(points,points.map(()=>[.4,.75,1]),.014));
  $('sceneStamp').textContent=`世界坐标：${data.frame_id} · 分析点云时间 ${data.stamp?.toFixed(3)} · revision ${data.revision}`;lastScene=data;
  if(!fitOnce&&(data.points||[]).length){fit();fitOnce=true;}}
function drawBoxes(){dispose(boxGroup);if(!state)return;for(const r of state.map.history){if(r.life_state==='VACATED'&&!$('showHistory').checked)continue;const g=r.geometry,center=g.body_center_map?.value,rotation=g.body_orientation_map?.value;const color=r.life_state==='VACATED'?0x7b8494:r.life_state==='MISSING_CANDIDATE'?0xffa53b:0x69dda1;
    if(center&&rotation){const geo=new THREE.EdgesGeometry(new THREE.BoxGeometry(...r.dimensions));const lines=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color}));lines.position.fromArray(center);const mat=new THREE.Matrix4().set(rotation[0][0],rotation[0][1],rotation[0][2],0,rotation[1][0],rotation[1][1],rotation[1][2],0,rotation[2][0],rotation[2][1],rotation[2][2],0,0,0,0,1);lines.quaternion.setFromRotationMatrix(mat);boxGroup.add(lines);}
    const poly=r.face.polygon;const geometry=new THREE.BufferGeometry().setFromPoints([...poly,poly[0]].map(p=>new THREE.Vector3(...p)));boxGroup.add(new THREE.Line(geometry,new THREE.LineBasicMaterial({color:r.face.trusted?0x67bfff:0xffae48})));
    const p=[...(center||r.face.center)];p[2]+=.3;boxGroup.add(label(`ID ${r.box_id}`,p,'#b7f3d1'));}}
function fit(){const b=new THREE.Box3();if(boxGroup.children.length)b.setFromObject(boxGroup);else b.setFromObject(rawGroup);if(b.isEmpty())return;const c=b.getCenter(new THREE.Vector3()),size=Math.max(.5,b.getSize(new THREE.Vector3()).length());controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(size*.7,-size*.8,size*.65));controls.update();}
$('fit').onclick=fit;$('showHistory').onchange=drawBoxes;
new ResizeObserver(()=>{const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe($('scene'));
let lastRender=0;function animate(t=0){requestAnimationFrame(animate);if(document.hidden||t-lastRender<33)return;lastRender=t;rawGroup.visible=$('showRaw').checked;expectedGroup.visible=$('showExpected').checked;boxGroup.visible=$('showBoxes').checked;controls.update();renderer.render(scene,camera);}animate();
function display(s){state=s;const m=s.map,source=s.source;const warning=s.error||source.error;const live=source.source==='SYNTHETIC_NOT_ODIN'?'合成场景 · 非相机数据':source.source==='RECORDED_ODIN_RAW'?'Odin 历史录制 · 几何只读验证':'实时 Odin · 原始 DTOF';$('source').textContent=`${live} · ${source.frame_id||'map'} · 会话 ${m.session_id.slice(0,8)}`;
  $('health').className=warning?'warn':'good';$('health').textContent=warning?tr(warning):'数据链路运行中';$('mode').value=s.mode;$('ready').checked=s.robot_ready;
  const candidates=m.history.filter(r=>r.life_state==='TENTATIVE');
  $('metrics').innerHTML=[['库存',m.inventory.length],['待确认新箱',candidates.length],['当前测量',m.current_measurements.length],['可执行候选',m.execution_candidates.length],['地图版本',m.revision]].map(([a,b])=>`<div class="metric"><strong>${b}</strong>${a}</div>`).join('');
  $('commit').textContent=`提交：${tr(s.commit.reason)} · 当前批次 ${s.samples_collected}/${s.config.epoch_size}`;$('policy').textContent=`策略建议：${s.policy.action} · ID ${s.policy.target_ids.join(', ')||'无'}`;
  $('timings').innerHTML=Object.entries(s.timing_ms).map(([k,v])=>`<div>${esc(k)} <strong>${v.toFixed(1)} ms</strong></div>`).join('')+`<div>当前进程 CPU ${s.process_cpu_percent.toFixed(1)}%（100%=1 核）</div>`;
  $('input').textContent=`首回波语义：${source.return_semantics||'未验证'}；图像年龄 ${source.image_age_s??'—'} s；点云年龄 ${source.cloud_age_s??'—'} s；P95 ${s.performance.p95_ms?.toFixed(1)??'—'} ms`;
  $('inventory').innerHTML=m.inventory.length?m.inventory.map(r=>`<tr><td>${r.box_id}</td><td>${tr(r.life_state)}</td><td>${tr(r.visibility)}</td><td>${tr(r.identity_status)}</td><td>${xyz(r.geometry.body_center_map.value)}</td><td>${tr(r.geometry.body_center_map.status)}</td><td>${xyz(r.geometry.face_center_map.value)}</td><td>${tr(r.geometry.body_orientation_map.status)}</td><td>${r.existence_probability.toFixed(2)}</td><td>${r.clear_run}</td><td class="${r.review_clear_runs>=2?'warn':''}">${r.review_clear_runs>=2?'待人工核实 · ':''}${r.review_clear_runs||0}</td><td>${esc((r.last_evidence.kinds||[]).map(tr).join(' / '))}</td></tr>`).join(''):'<tr><td colspan="12">尚无已确认库存。单次候选 / 几何不合格 / 只读回放不会伪装成库存。</td></tr>';
  $('candidates').innerHTML=candidates.length?candidates.map(r=>`<div class="row">ID ${r.box_id} · 观测 ${r.observations}/${s.config.min_observations} · 面中心 ${xyz(r.geometry.face_center_map.value)} · ${r.related_old_ids.length?'关联待复核旧箱 '+r.related_old_ids.join(', '):'独立新位置'}</div>`).join(''):'<div class="empty">当前没有待确认新箱。</div>';
  const d=s.diagnostics,entries=(d.observations||[]).map(o=>`<div class="row"><span class="tag">local ${o.local_id}</span>${tr(o.status)} · 位置 ${o.position_ok?'合格':'不合格'} · 姿态 ${o.orientation_ok?'合格':'不合格'} · 完整实测面 ${o.full_measured_face?'是':'否'}</div>`);
  for(const r of d.rejected||[])entries.push(`<div class="row warn">local ${r.local_detection_id} 拒绝：${esc((r.rejection_reasons||[]).join(', '))}</div>`);
  for(const [id,e] of Object.entries(d.ray_evidence||{}))entries.push(`<div class="row"><span class="tag">全局 ID ${id}</span>${tr(e.kind)} · ${tr(e.reason)} · 有效点 ${e.points} · 覆盖 ${((e.coverage||0)*100).toFixed(0)}%</div>`);
  $('diagnostics').innerHTML=entries.join('')||'<p class="empty">等待检测</p>';
  $('events').innerHTML=m.events.slice(-10).reverse().map(e=>`<div class="row">revision ${e.revision} · ID ${e.box_id} · ${esc(e.type)}</div>`).join('')||'<p class="empty">暂无事件</p>';
  $('measurements').textContent=JSON.stringify(m.current_measurements,null,2);$('fullState').textContent=JSON.stringify(s,null,2);
  const ss=s.scheduler.session;$('session').textContent=ss?`${ss.kind} · ${ss.state} · 视角 ${ss.views[ss.view_index]} · ${ss.collected}/${s.config.epoch_size} · ${ss.reason} · 覆盖 ${s.scheduler.covered_cells}/100 · 提交 ${ss.map_commit_ok} · 批次移除完成 ${ss.wall_batch_verified_complete}`:'未启动；无云台时需人工按提示转动 Odin。';$('ack').disabled=!ss||ss.state!=='WAIT_OPERATOR';
  const result=s.command_results.at(-1);if(result)$('command').textContent=result.ok===false?`命令失败：${result.error}`:`命令结果：${result.status||result.action||'完成'}`;
  $('imageStamp').textContent=`实时图像时间 ${s.preview_stamp?.toFixed(3)??'—'}；检测标注对应右侧分析点云时间，暂停或移动时请切换实时原图。`;
  if(lastRevision!==m.revision){drawBoxes();lastRevision=m.revision;}
}
async function poll(){try{const response=await fetch('/api/state');display(await response.json());const data=await (await fetch('/api/scene')).json();if(data.capture_id&&data.capture_id!==lastScene?.capture_id)drawScene(data);}catch(e){$('health').textContent=`服务连接失败：${e.message}`;$('health').className='bad';}setTimeout(poll,250);}poll();
let imageUrl=null;async function refreshImage(){try{const endpoint=$('depthView').checked?'/depth.jpg':$('rawView').checked||state?.mode==='paused'?'/raw.jpg':'/image.jpg';const r=await fetch(endpoint);if(r.status===200){const blob=await r.blob();const url=URL.createObjectURL(blob);$('image').src=url;$('image').style.display='block';$('imageEmpty').style.display='none';if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=url;}}catch(e){}setTimeout(refreshImage,100);}refreshImage();
